// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright The WasmEdge Authors

//===-- wasmedge/test/wide_arithmetic/WideArithTest.cpp -------------------===//
//
// GTest coverage for the Wide Arithmetic proposal (Phase 3):
//   i64.add128, i64.sub128, i64.mul_wide_s, i64.mul_wide_u
//
// Tests: interpreter path, AOT/LLVM path, proposal gating, serializer roundtrip.
//===----------------------------------------------------------------------===//

#include "common/configure.h"
#include "common/types.h"
#include "loader/loader.h"
#include "loader/serialize.h"
#include "vm/vm.h"

#ifdef WASMEDGE_USE_LLVM
#include "llvm/codegen.h"
#include "llvm/compiler.h"
#include "llvm/jit.h"
#endif

#include "gtest/gtest.h"

#include <array>
#include <cstdint>
#include <filesystem>
#include <limits>
#include <string_view>
#include <vector>

namespace {

using namespace WasmEdge;

// Hand-assembled WASM module: 14 test functions, each () -> (i64, i64).
// Generated by gen_wasm.py from the Wide Arithmetic proposal spec.
// 458 bytes, 14 test functions
static const std::array<WasmEdge::Byte, 458> WideArithWasm{{
    0x00, 0x61, 0x73, 0x6D, 0x01, 0x00, 0x00, 0x00, 0x01, 0x06, 0x01, 0x60, 0x00, 0x02, 0x7E, 0x7E,
    0x03, 0x0F, 0x0E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x07, 0xF1, 0x01, 0x0E, 0x0B, 0x61, 0x64, 0x64, 0x31, 0x32, 0x38, 0x5F, 0x7A, 0x65, 0x72,
    0x6F, 0x00, 0x00, 0x0C, 0x61, 0x64, 0x64, 0x31, 0x32, 0x38, 0x5F, 0x63, 0x61, 0x72, 0x72, 0x79,
    0x00, 0x01, 0x0B, 0x61, 0x64, 0x64, 0x31, 0x32, 0x38, 0x5F, 0x77, 0x72, 0x61, 0x70, 0x00, 0x02,
    0x0D, 0x73, 0x75, 0x62, 0x31, 0x32, 0x38, 0x5F, 0x73, 0x69, 0x6D, 0x70, 0x6C, 0x65, 0x00, 0x03,
    0x0D, 0x73, 0x75, 0x62, 0x31, 0x32, 0x38, 0x5F, 0x62, 0x6F, 0x72, 0x72, 0x6F, 0x77, 0x00, 0x04,
    0x0B, 0x73, 0x75, 0x62, 0x31, 0x32, 0x38, 0x5F, 0x77, 0x72, 0x61, 0x70, 0x00, 0x05, 0x11, 0x6D,
    0x75, 0x6C, 0x5F, 0x77, 0x69, 0x64, 0x65, 0x5F, 0x75, 0x5F, 0x73, 0x69, 0x6D, 0x70, 0x6C, 0x65,
    0x00, 0x06, 0x0E, 0x6D, 0x75, 0x6C, 0x5F, 0x77, 0x69, 0x64, 0x65, 0x5F, 0x75, 0x5F, 0x6D, 0x61,
    0x78, 0x00, 0x07, 0x0E, 0x6D, 0x75, 0x6C, 0x5F, 0x77, 0x69, 0x64, 0x65, 0x5F, 0x75, 0x5F, 0x6F,
    0x6E, 0x65, 0x00, 0x08, 0x0E, 0x6D, 0x75, 0x6C, 0x5F, 0x77, 0x69, 0x64, 0x65, 0x5F, 0x73, 0x5F,
    0x70, 0x6F, 0x73, 0x00, 0x09, 0x0F, 0x6D, 0x75, 0x6C, 0x5F, 0x77, 0x69, 0x64, 0x65, 0x5F, 0x73,
    0x5F, 0x6E, 0x65, 0x67, 0x31, 0x00, 0x0A, 0x11, 0x6D, 0x75, 0x6C, 0x5F, 0x77, 0x69, 0x64, 0x65,
    0x5F, 0x73, 0x5F, 0x6E, 0x65, 0x67, 0x6D, 0x69, 0x78, 0x00, 0x0B, 0x11, 0x6D, 0x75, 0x6C, 0x5F,
    0x77, 0x69, 0x64, 0x65, 0x5F, 0x73, 0x5F, 0x6D, 0x69, 0x6E, 0x76, 0x61, 0x6C, 0x00, 0x0C, 0x13,
    0x6D, 0x75, 0x6C, 0x5F, 0x77, 0x69, 0x64, 0x65, 0x5F, 0x73, 0x5F, 0x6D, 0x69, 0x6E, 0x5F, 0x6E,
    0x65, 0x67, 0x31, 0x00, 0x0D, 0x0A, 0xB2, 0x01, 0x0E, 0x0C, 0x00, 0x42, 0x00, 0x42, 0x00, 0x42,
    0x00, 0x42, 0x00, 0xFC, 0x13, 0x0B, 0x0C, 0x00, 0x42, 0x7F, 0x42, 0x00, 0x42, 0x01, 0x42, 0x00,
    0xFC, 0x13, 0x0B, 0x0C, 0x00, 0x42, 0x7F, 0x42, 0x7F, 0x42, 0x01, 0x42, 0x00, 0xFC, 0x13, 0x0B,
    0x0C, 0x00, 0x42, 0x0A, 0x42, 0x00, 0x42, 0x03, 0x42, 0x00, 0xFC, 0x14, 0x0B, 0x0C, 0x00, 0x42,
    0x00, 0x42, 0x01, 0x42, 0x01, 0x42, 0x00, 0xFC, 0x14, 0x0B, 0x0C, 0x00, 0x42, 0x00, 0x42, 0x00,
    0x42, 0x01, 0x42, 0x00, 0xFC, 0x14, 0x0B, 0x08, 0x00, 0x42, 0x03, 0x42, 0x05, 0xFC, 0x16, 0x0B,
    0x08, 0x00, 0x42, 0x7F, 0x42, 0x7F, 0xFC, 0x16, 0x0B, 0x08, 0x00, 0x42, 0x7F, 0x42, 0x01, 0xFC,
    0x16, 0x0B, 0x08, 0x00, 0x42, 0x06, 0x42, 0x07, 0xFC, 0x15, 0x0B, 0x08, 0x00, 0x42, 0x7F, 0x42,
    0x7F, 0xFC, 0x15, 0x0B, 0x08, 0x00, 0x42, 0x7F, 0x42, 0x02, 0xFC, 0x15, 0x0B, 0x1A, 0x00, 0x42,
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x7F, 0x42, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x7F, 0xFC, 0x15, 0x0B, 0x11, 0x00, 0x42, 0x80, 0x80, 0x80, 0x80, 0x80,
    0x80, 0x80, 0x80, 0x80, 0x7F, 0x42, 0x7F, 0xFC, 0x15, 0x0B
}};

// Helper: run a named export on an already-instantiated VM, expect (lo, hi).
static void CheckResult(VM::VM &VMInst, std::string_view Name,
                        int64_t ExpLo, int64_t ExpHi) {
  // Single-argument execute is unambiguous (avoids the 2-string_view overload).
  auto Res = VMInst.execute(Name);
  ASSERT_TRUE(Res) << "execute(" << Name << ") failed";
  ASSERT_EQ(Res->size(), 2U) << Name << ": expected 2 results";
  // Execute returns vector<pair<ValVariant, ValType>>; extract via .first.
  // Template call extracted to avoid '<' misparse inside EXPECT_EQ macro.
  int64_t Lo = (*Res)[0].first.get<int64_t>();
  int64_t Hi = (*Res)[1].first.get<int64_t>();
  EXPECT_EQ(Lo, ExpLo) << Name << " result_lo mismatch";
  EXPECT_EQ(Hi, ExpHi) << Name << " result_hi mismatch";
}

// -----------------------------------------------------------------------
// Interpreter fixture
// -----------------------------------------------------------------------
class WideArithInterp : public ::testing::Test {
protected:
  void SetUp() override {
    ASSERT_TRUE(VM.loadWasm(WideArithWasm));
    ASSERT_TRUE(VM.validate());
    ASSERT_TRUE(VM.instantiate());
  }
  // Proposal must be set before VM is constructed below (member init order),
  // not in SetUp() -- VM would already have copied Conf's state by then.
  Configure Conf{Proposal::WideArithmetic};
  VM::VM VM{Conf};
};

TEST_F(WideArithInterp, add128_zero) {
  CheckResult(VM, "add128_zero", 0, 0);
}
TEST_F(WideArithInterp, add128_carry) {
  // (UINT64_MAX, 0) + (1, 0) = (0, 1)  — carry propagates from lo to hi
  CheckResult(VM, "add128_carry", 0, 1);
}
TEST_F(WideArithInterp, add128_wrap) {
  // (UINT64_MAX, UINT64_MAX) + (1, 0) = (0, 0)  — 128-bit wraparound
  CheckResult(VM, "add128_wrap", 0, 0);
}
TEST_F(WideArithInterp, sub128_simple) {
  CheckResult(VM, "sub128_simple", 7, 0);
}
TEST_F(WideArithInterp, sub128_borrow) {
  // (0, 1) - (1, 0) = (UINT64_MAX, 0)  — borrow propagates from hi to lo
  CheckResult(VM, "sub128_borrow", -1, 0);
}
TEST_F(WideArithInterp, sub128_wrap) {
  // (0, 0) - (1, 0) = (UINT64_MAX, UINT64_MAX)  — 128-bit borrow/wrap
  CheckResult(VM, "sub128_wrap", -1, -1);
}
TEST_F(WideArithInterp, mul_wide_u_simple) {
  CheckResult(VM, "mul_wide_u_simple", 15, 0);
}
TEST_F(WideArithInterp, mul_wide_u_max) {
  // UINT64_MAX * UINT64_MAX = 0xFFFFFFFFFFFFFFFE_0000000000000001
  CheckResult(VM, "mul_wide_u_max", 1, -2);
}
TEST_F(WideArithInterp, mul_wide_u_one) {
  // UINT64_MAX * 1 = (UINT64_MAX, 0)
  CheckResult(VM, "mul_wide_u_one", -1, 0);
}
TEST_F(WideArithInterp, mul_wide_s_pos) {
  CheckResult(VM, "mul_wide_s_pos", 42, 0);
}
TEST_F(WideArithInterp, mul_wide_s_neg1) {
  // (-1) * (-1) = 1
  CheckResult(VM, "mul_wide_s_neg1", 1, 0);
}
TEST_F(WideArithInterp, mul_wide_s_negmix) {
  // (-1) * 2 = -2 as int128 -> lo=0xFFFFFFFFFFFFFFFE hi=0xFFFFFFFFFFFFFFFF
  CheckResult(VM, "mul_wide_s_negmix", -2, -1);
}
TEST_F(WideArithInterp, mul_wide_s_minval) {
  // INT64_MIN * INT64_MIN = 2^126 -> lo=0 hi=0x4000000000000000
  CheckResult(VM, "mul_wide_s_minval", 0,
              INT64_C(0x4000000000000000));
}
TEST_F(WideArithInterp, mul_wide_s_min_neg1) {
  // INT64_MIN * (-1) = 2^63 -> lo=0x8000000000000000 hi=0
  CheckResult(VM, "mul_wide_s_min_neg1",
              std::numeric_limits<int64_t>::min(), 0);
}

// -----------------------------------------------------------------------
// AOT fixture — compiles the same WASM bytes to native code first
// -----------------------------------------------------------------------
#ifdef WASMEDGE_USE_LLVM
class WideArithAOT : public ::testing::Test {
protected:
  void SetUp() override {
    Conf.getCompilerConfigure().setOutputFormat(
        CompilerConfigure::OutputFormat::Native);

    // Compile WASM -> native .so
    LLVM::Compiler Compiler(Conf);
    LLVM::CodeGen CodeGen(Conf);
    ASSERT_TRUE(Compiler.checkConfigure());
    Loader::Loader Ldr(Conf);
    Validator::Validator Val(Conf);
    auto Mod = Ldr.parseModule(WideArithWasm);
    ASSERT_TRUE(Mod);
    ASSERT_TRUE(Val.validate(**Mod));
    auto Data = Compiler.compile(**Mod);
    ASSERT_TRUE(Data);
    ASSERT_TRUE(CodeGen.codegen(WideArithWasm, std::move(*Data), AotPath));

    ASSERT_TRUE(VM.loadWasm(AotPath));
    ASSERT_TRUE(VM.validate());
    ASSERT_TRUE(VM.instantiate());
  }

  void TearDown() override {
    std::filesystem::remove(AotPath);
  }

  std::filesystem::path AotPath{std::filesystem::temp_directory_path() /
                                "wide_arith_test.so"};
  // Same ordering requirement as WideArithInterp above.
  Configure Conf{Proposal::WideArithmetic};
  VM::VM VM{Conf};
};

TEST_F(WideArithAOT, add128_zero)     { CheckResult(VM, "add128_zero", 0, 0); }
TEST_F(WideArithAOT, add128_carry)    { CheckResult(VM, "add128_carry", 0, 1); }
TEST_F(WideArithAOT, add128_wrap)     { CheckResult(VM, "add128_wrap", 0, 0); }
TEST_F(WideArithAOT, sub128_simple)   { CheckResult(VM, "sub128_simple", 7, 0); }
TEST_F(WideArithAOT, sub128_borrow)   { CheckResult(VM, "sub128_borrow", -1, 0); }
TEST_F(WideArithAOT, sub128_wrap)     { CheckResult(VM, "sub128_wrap", -1, -1); }
TEST_F(WideArithAOT, mul_wide_u_simple) { CheckResult(VM, "mul_wide_u_simple", 15, 0); }
TEST_F(WideArithAOT, mul_wide_u_max)  { CheckResult(VM, "mul_wide_u_max", 1, -2); }
TEST_F(WideArithAOT, mul_wide_u_one)  { CheckResult(VM, "mul_wide_u_one", -1, 0); }
TEST_F(WideArithAOT, mul_wide_s_pos)  { CheckResult(VM, "mul_wide_s_pos", 42, 0); }
TEST_F(WideArithAOT, mul_wide_s_neg1) { CheckResult(VM, "mul_wide_s_neg1", 1, 0); }
TEST_F(WideArithAOT, mul_wide_s_negmix) { CheckResult(VM, "mul_wide_s_negmix", -2, -1); }
TEST_F(WideArithAOT, mul_wide_s_minval) {
  CheckResult(VM, "mul_wide_s_minval", 0, INT64_C(0x4000000000000000));
}
TEST_F(WideArithAOT, mul_wide_s_min_neg1) {
  CheckResult(VM, "mul_wide_s_min_neg1", std::numeric_limits<int64_t>::min(), 0);
}

// -----------------------------------------------------------------------
// JIT fixture — VM compiles in-memory via ORC LLJIT at instantiate time.
// This is a genuinely different path from AOT: no .so on disk, code is
// loaded through LLVM::JIT/OrcLLJIT's relocation and symbol-resolution
// machinery instead of dlopen. It shares the same IR lowering
// (numericInstr.cpp) as AOT, but that's a reason to expect it to work, not
// a substitute for testing it: VM::unsafeLoadJITExecutable() logs and
// swallows any JIT failure and silently falls back to the interpreter, so
// a VM-only test could "pass" on interpreter results without JIT ever
// having run. We drive Compiler+JIT independently first to assert the JIT
// path itself succeeds, then use VM for the actual multi-value-return
// execution.
// -----------------------------------------------------------------------
Configure makeJITConfigure() {
  Configure C{Proposal::WideArithmetic};
  C.getRuntimeConfigure().setRunMode(RunMode::JIT);
  return C;
}

class WideArithJIT : public ::testing::Test {
protected:
  void SetUp() override {
    LLVM::Compiler Compiler(Conf);
    ASSERT_TRUE(Compiler.checkConfigure());
    Loader::Loader Ldr(Conf);
    Validator::Validator Val(Conf);
    auto Mod = Ldr.parseModule(WideArithWasm);
    ASSERT_TRUE(Mod);
    ASSERT_TRUE(Val.validate(**Mod));
    auto Data = Compiler.compile(**Mod);
    ASSERT_TRUE(Data) << "JIT-path LLVM compilation failed for wide-arithmetic";
    LLVM::JIT Jit(Conf);
    auto Exec = Jit.load(std::move(*Data));
    ASSERT_TRUE(Exec) << "ORC LLJIT load failed for wide-arithmetic module";

    ASSERT_TRUE(VM.loadWasm(WideArithWasm));
    ASSERT_TRUE(VM.validate());
    ASSERT_TRUE(VM.instantiate());
  }

  // Same ordering requirement as WideArithInterp above: RunMode must be set
  // before VM is constructed.
  Configure Conf{makeJITConfigure()};
  VM::VM VM{Conf};
};

TEST_F(WideArithJIT, add128_zero)     { CheckResult(VM, "add128_zero", 0, 0); }
TEST_F(WideArithJIT, add128_carry)    { CheckResult(VM, "add128_carry", 0, 1); }
TEST_F(WideArithJIT, add128_wrap)     { CheckResult(VM, "add128_wrap", 0, 0); }
TEST_F(WideArithJIT, sub128_simple)   { CheckResult(VM, "sub128_simple", 7, 0); }
TEST_F(WideArithJIT, sub128_borrow)   { CheckResult(VM, "sub128_borrow", -1, 0); }
TEST_F(WideArithJIT, sub128_wrap)     { CheckResult(VM, "sub128_wrap", -1, -1); }
TEST_F(WideArithJIT, mul_wide_u_simple) { CheckResult(VM, "mul_wide_u_simple", 15, 0); }
TEST_F(WideArithJIT, mul_wide_u_max)  { CheckResult(VM, "mul_wide_u_max", 1, -2); }
TEST_F(WideArithJIT, mul_wide_u_one)  { CheckResult(VM, "mul_wide_u_one", -1, 0); }
TEST_F(WideArithJIT, mul_wide_s_pos)  { CheckResult(VM, "mul_wide_s_pos", 42, 0); }
TEST_F(WideArithJIT, mul_wide_s_neg1) { CheckResult(VM, "mul_wide_s_neg1", 1, 0); }
TEST_F(WideArithJIT, mul_wide_s_negmix) { CheckResult(VM, "mul_wide_s_negmix", -2, -1); }
TEST_F(WideArithJIT, mul_wide_s_minval) {
  CheckResult(VM, "mul_wide_s_minval", 0, INT64_C(0x4000000000000000));
}
TEST_F(WideArithJIT, mul_wide_s_min_neg1) {
  CheckResult(VM, "mul_wide_s_min_neg1", std::numeric_limits<int64_t>::min(), 0);
}
#endif // WASMEDGE_USE_LLVM

// -----------------------------------------------------------------------
// Proposal gating: WASM must be rejected when WideArithmetic is disabled
// -----------------------------------------------------------------------
TEST(WideArithGating, RejectedWhenDisabled) {
  Configure Conf;
  Conf.removeProposal(Proposal::WideArithmetic);
  VM::VM VMInst(Conf);
  // The loader calls isInstrNeedProposal() and must reject the module.
  EXPECT_FALSE(VMInst.loadWasm(WideArithWasm));
}

TEST(WideArithGating, AcceptedWhenEnabled) {
  Configure Conf;
  Conf.addProposal(Proposal::WideArithmetic);
  VM::VM VMInst(Conf);
  EXPECT_TRUE(VMInst.loadWasm(WideArithWasm));
  EXPECT_TRUE(VMInst.validate());
  EXPECT_TRUE(VMInst.instantiate());
}

// -----------------------------------------------------------------------
// Serializer roundtrip: load -> serialize -> reload -> execute
// -----------------------------------------------------------------------
TEST(WideArithRoundtrip, SerializerRoundtrip) {
  Configure Conf;
  Conf.addProposal(Proposal::WideArithmetic);

  // Step 1: Parse to AST
  Loader::Loader Ldr(Conf);
  auto ModRes = Ldr.parseModule(WideArithWasm);
  ASSERT_TRUE(ModRes);

  // Step 2: Serialize AST back to bytes
  Loader::Serializer Ser(Conf);
  auto SerRes = Ser.serializeModule(**ModRes);
  ASSERT_TRUE(SerRes);
  const std::vector<Byte> &SerBytes = *SerRes;

  // Serialized bytes must be non-empty and start with the WASM magic
  ASSERT_GE(SerBytes.size(), 8U);
  EXPECT_EQ(SerBytes[0], 0x00U);
  EXPECT_EQ(SerBytes[1], 0x61U);
  EXPECT_EQ(SerBytes[2], 0x73U);
  EXPECT_EQ(SerBytes[3], 0x6DU);

  // Step 3: Reload from serialized bytes and execute
  VM::VM VMInst(Conf);
  ASSERT_TRUE(VMInst.loadWasm(SerBytes));
  ASSERT_TRUE(VMInst.validate());
  ASSERT_TRUE(VMInst.instantiate());

  // Spot-check a few functions to confirm semantic correctness after roundtrip
  CheckResult(VMInst, "add128_carry", 0, 1);
  CheckResult(VMInst, "sub128_borrow", -1, 0);
  CheckResult(VMInst, "mul_wide_u_max", 1, -2);
  CheckResult(VMInst, "mul_wide_s_minval", 0, INT64_C(0x4000000000000000));
  CheckResult(VMInst, "mul_wide_s_min_neg1",
              std::numeric_limits<int64_t>::min(), 0);
}

} // namespace

int main(int argc, char **argv) {
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
